#!/bin/sh
python PyDTI.py --method="nrlmf" --dataset="N1L1to5" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" > /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L6to10" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L11to15" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L16to20" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L21more" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt

python PyDTI.py --method="nrlmf" --dataset="N2L1to5" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L6to10" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L11to15" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L16to20" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L21more" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt

python PyDTI.py --method="nrlmf" --dataset="N3upL1to5" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL6to10" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL11to15" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL16to20" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL21more" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=25 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r25_iter300_results.txt

python PyDTI.py --method="nrlmf" --dataset="N1L1to5" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" > /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L6to10" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L11to15" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L16to20" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L21more" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt

python PyDTI.py --method="nrlmf" --dataset="N2L1to5" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L6to10" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L11to15" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L16to20" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L21more" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt

python PyDTI.py --method="nrlmf" --dataset="N3upL1to5" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL6to10" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL11to15" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL16to20" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL21more" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt


python PyDTI.py --method="nrlmf" --dataset="N1L1to5" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=100 max_iter=300" > /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r100_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L6to10" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=100 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r100_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L11to15" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=100 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r100_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L16to20" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=100 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r100_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L21more" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=100 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r100_iter300_results.txt

python PyDTI.py --method="nrlmf" --dataset="N2L1to5" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=100 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r100_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L6to10" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=100 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r100_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L11to15" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=100 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r100_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L16to20" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=100 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r100_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L21more" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=100 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r100_iter300_results.txt

python PyDTI.py --method="nrlmf" --dataset="N3upL1to5" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=100 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r100_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL6to10" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=100 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r100_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL11to15" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=100 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r100_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL16to20" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=100 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r100_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL21more" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r50_iter300_results.txt

python PyDTI.py --method="nrlmf" --dataset="N1L1to5" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" > /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L6to10" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L11to15" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L16to20" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1L21more" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt

python PyDTI.py --method="nrlmf" --dataset="N2L1to5" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L6to10" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L11to15" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L16to20" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2L21more" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt

python PyDTI.py --method="nrlmf" --dataset="N3upL1to5" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL6to10" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL11to15" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL16to20" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upL21more" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_numligand/" --cvs=1 --predict-num=5 --method-opt="r=150 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/r150_iter300_results.txt

