#!/bin/sh
python PyDTI.py --method="nrlmf" --dataset="N1Tc0.49to0.55" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" > /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1Tc0.55to0.6" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1Tc0.6to0.65" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1Tc0.65to0.7" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1Tc0.7to0.75" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1Tc0.75to0.8" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1Tc0.8to0.85" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1Tc0.85to0.9" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1Tc0.9to0.95" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N1Tc0.95to1" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt

python PyDTI.py --method="nrlmf" --dataset="N2Tc0.49to0.55" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2Tc0.55to0.6" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2Tc0.6to0.65" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2Tc0.65to0.7" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2Tc0.7to0.75" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2Tc0.75to0.8" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2Tc0.8to0.85" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2Tc0.85to0.9" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2Tc0.9to0.95" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N2Tc0.95to1" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt

python PyDTI.py --method="nrlmf" --dataset="N3upTc0.49to0.55" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upTc0.55to0.6" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upTc0.6to0.65" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upTc0.65to0.7" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upTc0.7to0.75" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upTc0.75to0.8" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upTc0.8to0.85" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upTc0.85to0.9" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upTc0.9to0.95" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
python PyDTI.py --method="nrlmf" --dataset="N3upTc0.95to1" --data-dir="/scratch/hansaim.lim/wiZAN/ZINC_data/chem_prot/numtarget_maxTc/" --cvs=1 --predict-num=5 --method-opt="r=50 max_iter=300" >> /scratch/hansaim.lim/PyDTI/NRLMF_on_ZINC/maxTc/r50_iter300_results.txt
