>P1;comp155_c0_seq1
sequence:comp155_c0_seq1:  1:   : 292:   :   :   :   :
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MAPLKCILLFLFFTTDLVIGVR
YSSGEGRID-----------------R----R----------------INRLLVHPLIKK
LVEEVERSGLEHEGLYRLSGSKT----EVQKLEKDCQ----FLDTD-ISQYDVTAITSYL
KELFRNLRP-SLIDETTFNQLSDALKMENSEDLKNKITDIIIKLPQDIRDTLAYLMVHLQ
KVVEKKEINRMNPKNIGIVFGPTLMNSQYDDLMAAAALNNQQTKIIEKLLELPSSFWKEL
INYESTKTESNVSISKEDKEGAWGGAASADASASDEIVHPRSHLWSQIQGAKLKPISQVP
RRIVLSKPEDDLMDEES*
>P1;1f7c
structure:1f7c:  191:A  :381:A   :   :   :   :
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------AQLDSIGFSIIKK
CIHAVETRGINEQGLYRIVGVNS----RVQKLLSILMDPE----TEICAEWEIKTITSAL
KTYLRMLPG-PLMMYQFQRSFIKAAKLENQESRVSEIHSLVHRLPEKNRQMLHLLMNHLA
KVADNHKQNLMTVANLGVVFGPTLLRPTV----AAIMDIKFQNIVIEILIENHEKIFNTV
PE----------------------------------------------------------
-----------------*
>P1;1xa6
structure:1xa6:  22:A  :466:A   :   :   :   :
PIWKSYLYQLQQEAPRPKRIICPREVENRPKYYGREFHGIISREQADELLGGVEGAYILR
ESQRQPGCYTLALRFGNQTLNYRLFHDGKHFVGEKRFESIHDLVTDGLITLYIETKAAEY
ISKMTTN------PIYEHIGYATLLRYEKTHNFKVHTFRGPHWCEYCANFMWGLIAQGVR
CSDCGLNVHKQCSKHVP--NDCQPDLK----RIKKVYCCDLTTLV--KAHNTQRPMVVDI
CIREIEARGLKSEGLYRVSGFTE----HIEDVKMAFDRDGEKADISANVYPDINIITGAL
KLYFRDLPI-PVITYDTYSKFIDAAKISNADERLEAVHEVLMLLPPAHYETLRYLMIHLK
KVTMNEKDNFMNAENLGIVFGPTLMRPPEDSTLTTLHDMRYQKLIVQILIENEDVLF---
------------------------------------------------------------
-----------------*
