>P1;comp155_c0_seq1
sequence:comp155_c0_seq1:  1:   : 177:   :   :   :   :
RLLVHPLIKKLVEEVERSGLEHEGLYRLSGSKTEVQKL--E---KDCQFL-DTD--ISQY--D-VTAITSYL
KELFRNLRPSLIDETTFNQLSDALKMENSEDLKNKITDIIIKLPQDIRDTLAYLMVHLQKVVEKKEINRMNP
KNIGIVFGPTLMNSQY--DDLMAAAALNNQQTKIIEKLLELPSSFW*
>P1;3wpq
structure:3wpq:  361:  A  :  539  :  A : : : :
--MIPSIVVHCVNEIEQRGLTETGLYRIAGCDRTVKEL--K---EKFLRV-KTVPLLSKV--DDIHAICSLL
KDFLRNLKEPLLTFRLNRAFMEAAEITDEDNSIAAMYQAVGELPQANRDTLAFLMIHLQRVAQSPH-TKMDV
ANLAKVFGPTIVAHAVPNPDPVTMSQDIKRQPKVVERLLSLPLEYW*
>P1;3byi
structure:3byi:  298: A  : 442: A :   :   :   :
-------VKQCIEAVEKRGLDVDGIYRVSGNLATIQKL--RFIVNQEEKL-NLD--DSQWE-D-IHVVTGAL
KMFFRELPEPLFPYSFFEQFVEAIKKQDNNTRIEAVKSLVQKLPPPNRDTMKVLFGHLTKIVAKASKNLMST
QSLGIVFGPTLLRAE-------------------------------*
>P1;3iug
structure:3iug: 396  : A  : 532  : A  :   :   :   :
--------------IERYGIV-DGIYRLSGVASNIQRLRHE---FDSEHVPDLT--KEPYVQD-IHSVGSLC
KLYFRELPNPLLTYQLYEKFSDAVSAATDEERLIKIHDVIQQLPPPHYRTLEFLMRHLSLLADYCSITNMHA
KNLAIVWAPNLLRS--------------------------------*
