>P1;comp155_c0_seq3
sequence:comp155_c0_seq3:  1:   : 180:   :   :   :   :
PVNRLTVHPLIIKLVEEVEKSGMQQEGLYRLSGSKTEVQKL------E---KDCQFL-DT-D---I-SQY--
DVTAITSYLKELFRNLRPSLIDETTFNQLSDALKMENSEDLKNKITDIIIKLPQDIRDTLAYLMVHLQKVVE
KKEINRMNPKNIGIVFGPTLMNSQ--YDDLMAAAALNNQQTKIIEKLLELPSSFW*
>P1;3wps
structure:3wps:  358:  A  :  539  :  A : : : :
--TSPMIPSIVVHCVNEIEQRGLTETGLYRIDGCDRTVKEL------K---E--KFL-RVKTVPLL-SKVD-
DIHAICSLLKDFLRNLKEPLLTFRLNRAFMEAAEITDEDNSIAAMYQAVGELPQANRDTLAFLMIHLQRVAQ
SP-HTKMDVANLAKVFGPTIVAHAVPNPDPVTMSQDIKRQPKVVERLLSLPLEYW*
>P1;3byi
structure:3byi:  293: A  : 442: A :   :   :   :
-----TVPWFVKQCIEAVEKRGLDVDGIYRVSGNLATIQKL------RFIVNQEEKL-NL-D---D-SQWE-
DIHVVTGALKMFFRELPEPLFPYSFFEQFVEAIKKQDNNTRIEAVKSLVQKLPPPNRDTMKVLFGHLTKIVA
KASKNLMSTQSLGIVFGPTLLRAE-------------------------------*
>P1;3iug
structure:3iug: 396  : A  : 532  : A  :   :   :   :
-----------------IERYGIV-DGIYRLSGVASNIQRLRH----E---FDSEHVPDL-T---K-EPYVQ
DIHSVGSLCKLYFRELPNPLLTYQLYEKFSDAVSAATDEERLIKIHDVIQQLPPPHYRTLEFLMRHLSLLAD
YCSITNMHAKNLAIVWAPNLLRS--------------------------------*
>P1;1f7c
structure:1f7c: 200  : A  : 370  : A  :   :   :   :
---------IIKKCIHAVETRGINEQGLYRIVGVNSRVQKLLSILMDP----------ET-E---ICAEW--
EIKTITSALKTYLRMLPGPLMMYQFQRSFIKAAKLENQESRVSEIHSLVHRLPEKNRQMLHLLMNHLAKVAD
NHKQNLMTVANLGVVFGPTLLRP------TVAAIMDIKFQNIVIEILIE------*
