>P1;comp155_c0_seq1
sequence:comp155_c0_seq1:  21:   : 292:   :   :   :   :
VRYSSGEGRIDRRINRL--LVHPLIKKLVEEVERSGLEHEGLYRLSGSKTEVQKLEKDCQFLDT----D---
---ISQ---Y-D-VTAITSYLKELFRNLRPSLIDETTFNQLSDALKMENSEDLKNKITDIIIKLPQDIRDTL
AYLMVHLQKVVEKKEINRMNPKNIGIVFGPTLMNSQ--Y--DDLMAAAALNN--QQTKIIEKLLELPSSFWK
ELINYESTKTESNVSISKEDKEGAWGGAASADASASDEIVHPRSHLWSQIQGAKLKPISQVPRRIVLSKPED
DLMDEES*

>P1;2mbg
structure:2mbg:356:  A  :  446  :  A : : : :
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------------------------------------------VLYVFFTHVQELFG
NVVLKQVMKPLRWSNMATMPTLPETQAGIKEEIRRQEFLLNCLHRDLQGGIKDLSKEERLWEVQRILTALKR
KLREA--*

>P1;3wpq
structure:3wpq:347:A:545:A::::
-----GEGMLADFVSQTSPMIPSIVVHCVNEIEQRGLTETGLYRIAGCDRTVKELKEKFLRVKT----VPL-
---LSK---V-DDIHAICSLLKDFLRNLKEPLLTFRLNRAFMEAAEITDEDNSIAAMYQAVGELPQANRDTL
AFLMIHLQRVAQSPH-TKMDVANLAKVFGPTIVAHA--VPNPDPVTMSQDIK--RQPKVVERLLSLPLEYWS
QFMMV-------------------------------------------------------------------
-------*

>P1;3wps
structure:3wps:347:A:546:A::::
-----GEGMLADFVSQTSPMIPSIVVHCVNEIEQRGLTETGLYRIDGCDRTVKELKEKFLRVKT----VPL-
---LSK---V-DDIHAICSLLKDFLRNLKEPLLTFRLNRAFMEAAEITDEDNSIAAMYQAVGELPQANRDTL
AFLMIHLQRVAQSPH-TKMDVANLAKVFGPTIVAHA--VPNPDPVTMSQDIK--RQPKVVERLLSLPLEYWS
QFMMVE------------------------------------------------------------------
-------*

>P1;3w6r
structure:3w6r:361:A:546:A::::
-------------------MIPSIVVHCVNEIEQRGLTETGLYRISGCDRTVKELKEKFLRVKT----VPL-
---LSK---V-DDIHAICSLLKDFLRNLKEPLLTFRLNRAFMEAAEITDEDNSIAAMYQAVGELPQANRDTL
AFLMIHLQRVAQSPH-TKMDVANLAKVFGPTIVAHA--V--PNPDPVTMLQDIKRQPKVVERLLSLPLEYWS
QFMMVE------------------------------------------------------------------
-------*

>P1;3cxl
structure:3cxl:277:A:459:A::::
---------HTTKRPMV--VDM-----CIREIESRGLNSEGLYRVSGFSDLIEDVKM--AFDRDGEKAD---
---ISVNMYE-D-INIITGALKLYFRDLPIPLITYDAYPKFIESAKIMDPDEQLETLHEALKLLPPAHCETL
RYLMAHLKRVTLHEKENLMNAENLGIVFGPTLMRSP--E--LDAMAALNDIR--YQRLVVELLIKNEDILF-
------------------------------------------------------------------------
-------*

>P1;2ovj
structure:2ovj:357:A:546:A::::
--------QTSPMIPSI--VVH-----CVNEIEQRGLTETGLYRISGCDRTVKELKE--KFLRVKTVPL---
---LSK---VDD-IHAICSLLKDFLRNLKEPLLTFRLNRAFMEAAEITDEDNSIAAMYQAVGELPQANRDTL
AFLMIHLQRVAQSPH-TKMDVANLAKVFGPTIVAHAVPN--PDPVTMLQDIK--RQPKVVERLLSLPLEYWS
QFMMVE------------------------------------------------------------------
-------*

>P1;1f7c
structure:1f7c:194:A:381:A::::
----------DSIGFSI--IKK-----CIHAVETRGINEQGLYRIVGVNSRVQKLLS--ILMDPKTA-TETE
TEICAE---W-E-IKTITSALKTYLRMLPGPLMMYQFQRSFIKAAKLENQESRVSEIHSLVHRLPEKNRQML
HLLMNHLAKVADNHKQNLMTVANLGVVFGPTLLRPQ--E--ETV-AAIMDIK--FQNIVIEILIENHEKIFN
TVPE--------------------------------------------------------------------
-------*
