>P1;comp155_c0_seq1
sequence:comp155_c0_seq1:  21:   : 292:   :   :   :   :
VRYSSGEGRIDRRINRLLVHPLIKKLVEEVERSGLEHEGLYRLSGSKTEVQKLEKDCQFLDT----DISQY-
DVTAITSYLKELFRNLRPSLIDETTFNQLSDALKMENSEDLKNKITDIIIKLPQDIRDTLAYLMVHLQKVVE
KKEINRMNPKNIGIVFGPTLMNSQ--YDDLMAAAALNNQQTKIIEKLLELPSSFWKELINYESTKTESNVSI
SKEDKEGAWGGAASADASASDEIVHPRSHLWSQIQGAKLKPISQVPRRIVLSKPEDDLMDEES*

>P1;2mbg
structure:2mbg:  356:  A  :  446  :  A : : : :
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------VLYVFFTHVQELFGNVVLKQVMKPLRWSNM
ATMPTLPETQAGIKEEIRRQEFLLNCLHRDLQGGIKDLSKEERLWEVQRILTALKRKLREA--*

>P1;2ovj
structure:2ovj:  357: A  : 546: A :   :   :   :
--------QTSPMIPSIVVH-----CVNEIEQRGLTETGLYRISGCDRTVKELKE--KFLRVKTVPLLSKVD
DIHAICSLLKDFLRNLKEPLLTFRLNRAFMEAAEITDEDNSIAAMYQAVGELPQANRDTLAFLMIHLQRVAQ
SPH-TKMDVANLAKVFGPTIVAHAVPNPDPVTMLQDIKRQPKVVERLLSLPLEYWSQFMMVE----------
---------------------------------------------------------------*

>P1;3wpq
structure:3wpq: 347  : A  : 545  : A  :   :   :   :
-----GEGMLADFVSQTSPMIPSIVVHCVNEIEQRGLTETGLYRIAGCDRTVKELKEKFLRVKTVPLLSKVD
DIHAICSLLKDFLRNLKEPLLTFRLNRAFMEAAEITDEDNSIAAMYQAVGELPQANRDTLAFLMIHLQRVAQ
SPH-TKMDVANLAKVFGPTIVAHAVPNPDPVTMSQDIKRQPKVVERLLSLPLEYWSQFMMV-----------
---------------------------------------------------------------*
